'use strict';

import fs from 'node:fs/promises';
import path from 'path';
import debug from 'debug';
import crypto from 'node:crypto'
import QRCode from 'qrcode';

import { 
  isValidIPv4, 
  exec, 
  generateDefaultNft 
} from './Utility';

import ServerError from '../types/ServerError';
import env from '../config/env'
import Client from '../types/Client'
import ServerData from '../types/ServerData'
import ClientQuery from '../types/ClientQuery';

class WireGuard {

  private __configPromise: Promise<ServerData> | undefined

  async __buildConfig(): Promise<ServerData> {
    this.__configPromise = Promise.resolve().then(async () => {
      if (!env.WG_HOST) {
        throw new Error('WG_HOST Environment Variable Not Set!');
      }

      debug('Loading configuration...');
      let config;
      try {
        config = await fs.readFile(path.join(env.WG_PATH, 'wg0.json'), 'utf8');
        config = JSON.parse(config);
        debug('Configuration loaded.');
      } catch {
        const privateKey = await exec('wg genkey');
        const publicKey = await exec(`echo ${privateKey} | wg pubkey`, {
          log: 'echo ***hidden*** | wg pubkey',
        });
        const address = env.WG_DEFAULT_ADDRESS.replace('x', '1');

        config = {
          server: {
            privateKey,
            publicKey,
            address,
          },
          clients: {},
        };
        debug('Configuration generated.');
      }

      return config;
    });

    return this.__configPromise;
  }

  async getConfig() {
    if (!this.__configPromise) {
      const config = await this.__buildConfig();

      await this.__saveConfig(config);

      if (!env.WG_MANAGED) 
        return this.__configPromise;
      
      await exec(`wg-quick down ${path.join(env.WG_PATH, 'wg0.conf')}`).catch(() => {});
      await exec(`wg-quick up ${path.join(env.WG_PATH, 'wg0.conf')}`).catch((err) => {
        if (err && err.message && err.message.includes('Cannot find device "wg0"')) {
          throw new Error('WireGuard exited with the error: Cannot find device "wg0"\nThis usually means that your host\'s kernel does not support WireGuard!');
        }

        throw err;
      });
     
      await this.__syncConfig();
    }

    return this.__configPromise;
  }

  async saveConfig() {
    const config = await this.getConfig();
    if (config) {
      await this.__saveConfig(config);
    }
    
    if (env.WG_MANAGED) 
      await this.__syncConfig();
  }

  async __saveConfig(config: ServerData) {

    const defaultNft = generateDefaultNft(
      env.WG_DEFAULT_ADDRESS.replace('x', '0') + '/24',
      env.WG_PORT,
      'wg0'
    )

    let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${config.server.privateKey}
Address = ${config.server.address}/24
ListenPort = ${env.WG_PORT}
PreUp = ${env.WG_PRE_UP || ''}
PostUp = ${env.WG_POST_UP || (env.WG_MANAGED ? defaultNft.postUp : '')}
PreDown = ${env.WG_PRE_DOWN || ''}
PostDown = ${env.WG_POST_DOWN || (env.WG_MANAGED ? defaultNft.postDown : '')}
`;

    for (const [clientId, client] of Object.entries(config.clients)) {
      if (!client.enabled) continue;

      result += `

# Client: ${client.name} (${clientId})
[Peer]
PublicKey = ${client.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${client.address}/32`;
    }

    debug('Config saving...');
    await fs.writeFile(path.join(env.WG_PATH, 'wg0.json'), JSON.stringify(config, undefined, 2), {
      mode: 0o660,
    });
    await fs.writeFile(path.join(env.WG_PATH, 'wg0.conf'), result, {
      mode: 0o600,
    });
    debug('Config saved.');
  }

  async __syncConfig() {
    debug('Config syncing...');
    await exec(`wg syncconf wg0 <(wg-quick strip ${path.join(env.WG_PATH, 'wg0.conf')})`);
    debug('Config synced.');
  }

  async getClients() {
    const config = await this.getConfig();
    if (!config) {
      return;
    }

    const clients: Client[] = Object.entries(config.clients)
      .map(([clientId, client]) => ({
        id: clientId,
        name: client.name,
        enabled: client.enabled,
        address: client.address,
        publicKey: client.publicKey,
        createdAt: new Date(client.createdAt),
        updatedAt: new Date(client.updatedAt),
        allowedIPs: client.allowedIPs,
        downloadableConfig: 'privateKey' in client,
      } satisfies Client));

    if (!env.WG_MANAGED) 
        return clients;

    // Loop WireGuard status
    const dump: string = await exec('wg show wg0 dump', {
      log: false,
    });
    dump
      .trim()
      .split('\n')
      .slice(1)
      .forEach((line) => {
        const [
          publicKey,
          preSharedKey, // eslint-disable-line @typescript-eslint/no-unused-vars
          endpoint, // eslint-disable-line @typescript-eslint/no-unused-vars
          allowedIps, // eslint-disable-line @typescript-eslint/no-unused-vars
          latestHandshakeAt,
          transferRx,
          transferTx,
          persistentKeepalive,
        ] = line.split('\t');

        const client = clients.find((client) => client.publicKey === publicKey);
        if (!client) return;

        if (latestHandshakeAt !== '0')
          client.latestHandshakeAt = new Date(Number(`${latestHandshakeAt}000`));
    
        client.transferRx = Number(transferRx);
        client.transferTx = Number(transferTx);
        client.persistentKeepalive = Number(persistentKeepalive);
      });

    return clients;
  }

  async getClient(query: ClientQuery) {
    const config = await this.getConfig();
    if (!config || !query.clientId) return;

    const client = config.clients[query.clientId];
    if (!client) {
      throw new ServerError(`Client Not Found: ${query.clientId}`, 404);
    }

    return client;
  }

  async getClientConfiguration(query: ClientQuery) {
    const config = await this.getConfig();
    const client = await this.getClient(query);
    if (!config || !client) return;

    return `
[Interface]
PrivateKey = ${client.privateKey ? `${client.privateKey}` : 'REPLACE_ME'}
Address = ${client.address}/24
${env.WG_DEFAULT_DNS ? `DNS = ${env.WG_DEFAULT_DNS}\n` : ''}\
${env.WG_MTU ? `MTU = ${env.WG_MTU}\n` : ''}\

[Peer]
PublicKey = ${config.server.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${env.WG_ALLOWED_IPS}
PersistentKeepalive = ${env.WG_PERSISTENT_KEEPALIVE}
Endpoint = ${env.WG_HOST}:${env.WG_CONFIG_PORT}`;
  }

  async getClientQRCodeSVG(query: ClientQuery) {
    const config = await this.getClientConfiguration(query);
    if (!config) return;

    return QRCode.toString(config, {
      type: 'svg',
      width: 512,
    });
  }

  async createClient(query: ClientQuery) {
    if (!query.name) {
      throw new Error('Missing: Name');
    }

    const config = await this.getConfig();
    if (!config) return;

    const privateKey = await exec('wg genkey');
    const publicKey = await exec(`echo ${privateKey} | wg pubkey`, {
      log: 'echo ***hidden*** | wg pubkey',
    });
    const preSharedKey = await exec('wg genpsk');

    // Calculate next IP
    let address;
    for (let i = 2; i < 255; i++) {
      const client = Object.values(config.clients).find((client) => {
        return client.address === env.WG_DEFAULT_ADDRESS.replace('x', i.toString());
      });

      if (!client) {
        address = env.WG_DEFAULT_ADDRESS.replace('x', i.toString());
        break;
      }
    }

    if (!address) {
      throw new Error('Maximum number of clients reached.');
    }

    // Create Client
    const id: string = crypto.randomUUID();
    const client: Client = {
      id,
      name: query.name,
      address,
      privateKey,
      publicKey,
      preSharedKey,
      createdAt: new Date(),
      updatedAt: new Date(),
      enabled: true,
      allowedIPs: undefined
    };

    config.clients[id] = client;

    await this.saveConfig();

    return client;
  }

  async deleteClient(query: ClientQuery) {
    const config = await this.getConfig();
    if (!config || !query.clientId) return;

    if (config.clients[query.clientId]) {
      delete config.clients[query.clientId];
      await this.saveConfig();
    }
  }

  async enableClient(query: ClientQuery) {
    const client = await this.getClient(query);
    if (!client) return;

    client.enabled = true;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async disableClient(query: ClientQuery) {
    const client = await this.getClient(query);
    if (!client) return;

    client.enabled = false;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async updateClientName(query: ClientQuery) {
    const client = await this.getClient(query);
    if (!client || !query.name) return;

    client.name = query.name;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async updateClientAddress(query: ClientQuery) {
    const client = await this.getClient(query);
    if (!client) return;

    if (!query.address || !isValidIPv4(query.address)) {
      throw new ServerError(`Invalid Address: ${query.address}`, 400);
    }

    client.address = query.address;
    client.updatedAt = new Date();

    await this.saveConfig();
  }

  async __reloadConfig() {
    await this.__buildConfig();

    if (env.WG_MANAGED)
      await this.__syncConfig();
  }

  async restoreConfiguration(config: string) {
    debug('Starting configuration restore process.');
    const _config: ServerData = JSON.parse(config);
    await this.__saveConfig(_config);
    await this.__reloadConfig();
    debug('Configuration restore process completed.');
  }

  async backupConfiguration() {
    debug('Starting configuration backup.');
    const config = await this.getConfig();
    const backup = JSON.stringify(config, null, 2);
    debug('Configuration backup completed.');
    return backup;
  }

  async Shutdown() {
    if (env.WG_MANAGED)
      await exec(`wg-quick down ${path.join(env.WG_PATH, 'wg0.conf')}`).catch(() => {});
  }
};

export default WireGuard;