name: deploy

on:
  push:
    branches:
      - master
    paths:
      - src/**
  pull_request:
    branches:
      - master
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push using Podman
      run: |
        ACTOR=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        SHA=${{ github.sha }}
        podman build --squash \
          --build-arg REPO_URL="${{ github.server_url }}/${{ github.repository }}" \
          -t ghcr.io/$ACTOR/wg-easy:$SHA \
          -t ghcr.io/$ACTOR/wg-easy:latest \
          . --file Containerfile
        podman push ghcr.io/$ACTOR/wg-easy:$SHA
        podman push ghcr.io/$ACTOR/wg-easy:latest
        
